// ============================================================
// CUPSHE AI Skill Tree — Comprehensive Data
// Mapped to: 14 departments × 3 pilot projects × 4 layers
// Design: User-centric navigation with department & project filters
// ============================================================

export type SkillLayer = "foundation" | "department" | "scenario" | "system";
export type PilotProject = "marketing-ai" | "creative-ai" | "data-ai";

export interface SkillNode {
  id: string;
  titleZh: string;
  titleEn: string;
  descriptionZh: string;
  descriptionEn: string;
  layer: SkillLayer;
  level: number; // 1-5 difficulty
  maxLevel: number;
  departments: string[]; // which dept IDs this skill applies to
  pilotProjects: PilotProject[]; // which pilot projects
  progress: number; // 0-100
  prerequisites: string[]; // skill IDs required before this
  tools: string[]; // AI tools involved
  tags: string[];
}

export const layerConfig: Record<SkillLayer, { zh: string; en: string; color: string; bg: string; icon: string }> = {
  foundation: { zh: "全员基础", en: "Universal Foundation", color: "text-teal-600", bg: "bg-teal-50", icon: "🌱" },
  department: { zh: "部门职能", en: "Department Skills", color: "text-blue-600", bg: "bg-blue-50", icon: "🏢" },
  scenario: { zh: "业务场景", en: "Business Scenarios", color: "text-amber-600", bg: "bg-amber-50", icon: "🎯" },
  system: { zh: "系统进阶", en: "Advanced System", color: "text-purple-600", bg: "bg-purple-50", icon: "🚀" },
};

export const pilotProjectConfig: Record<PilotProject, { zh: string; en: string; color: string; bg: string }> = {
  "marketing-ai": { zh: "效果营销AI化", en: "Performance Marketing AI", color: "text-rose-600", bg: "bg-rose-50" },
  "creative-ai": { zh: "创意AI化", en: "Creative AI", color: "text-violet-600", bg: "bg-violet-50" },
  "data-ai": { zh: "数据分析AI化", en: "Data Analytics AI", color: "text-cyan-600", bg: "bg-cyan-50" },
};

export const departmentSkillMap: Record<string, { zh: string; en: string }> = {
  marketing: { zh: "营销中心", en: "Marketing Center" },
  operations: { zh: "运营中心", en: "Operation Center" },
  "multi-channel": { zh: "多渠道事业部", en: "Multi Channel Business" },
  "channel-dev": { zh: "渠道拓展部", en: "Channel Development" },
  product: { zh: "产品中心", en: "Product Center" },
  creative: { zh: "创意中心", en: "Creative Center" },
  "supply-chain": { zh: "生产供应链中心", en: "Supply Chain Center" },
  logistics: { zh: "仓储物流中心", en: "Warehousing & Logistics" },
  it: { zh: "互联网研发中心", en: "Internet R&D Center" },
  finance: { zh: "财务中心", en: "Finance Center" },
  "gm-office": { zh: "总经办", en: "GM Office" },
  hr: { zh: "人力资源中心", en: "HR Center" },
  audit: { zh: "审计监察部", en: "Audit & Supervision" },
  "board-secretary": { zh: "董秘办", en: "Board Secretary" },
};

export const skillNodes: SkillNode[] = [
  // ========== FOUNDATION (全员必修) ==========
  {
    id: "F01",
    titleZh: "AI认知与思维",
    titleEn: "AI Awareness & Mindset",
    descriptionZh: "理解AI基本概念、能力边界与发展趋势，建立AI-first思维模式，识别工作中的AI应用机会",
    descriptionEn: "Understand AI fundamentals, capabilities, limitations and trends. Build AI-first mindset and identify AI opportunities at work",
    layer: "foundation",
    level: 1, maxLevel: 3,
    departments: ["all"],
    pilotProjects: [],
    progress: 85,
    prerequisites: [],
    tools: ["ChatGPT", "Claude", "Gemini"],
    tags: ["必修", "入门"],
  },
  {
    id: "F02",
    titleZh: "Prompt Engineering基础",
    titleEn: "Prompt Engineering Basics",
    descriptionZh: "掌握与AI大模型有效沟通的技巧：指令设计、角色设定、Few-shot示例、上下文管理、输出格式控制",
    descriptionEn: "Master effective AI communication: instruction design, role setting, few-shot examples, context management, output format control",
    layer: "foundation",
    level: 1, maxLevel: 3,
    departments: ["all"],
    pilotProjects: [],
    progress: 78,
    prerequisites: ["F01"],
    tools: ["ChatGPT", "Claude"],
    tags: ["必修", "核心"],
  },
  {
    id: "F03",
    titleZh: "AI办公提效",
    titleEn: "AI Office Productivity",
    descriptionZh: "使用AI提升日常办公效率：文档撰写与润色、邮件处理、会议纪要生成、PPT制作、Excel数据分析",
    descriptionEn: "Boost daily productivity with AI: document writing, email handling, meeting notes, PPT creation, Excel data analysis",
    layer: "foundation",
    level: 1, maxLevel: 3,
    departments: ["all"],
    pilotProjects: [],
    progress: 72,
    prerequisites: ["F02"],
    tools: ["ChatGPT", "Copilot", "Gamma", "Claude"],
    tags: ["必修", "效率"],
  },
  {
    id: "F04",
    titleZh: "AI信息检索与研究",
    titleEn: "AI Research & Intelligence",
    descriptionZh: "利用AI进行高效信息搜索、竞品调研、行业趋势分析、研究报告生成、多源信息整合",
    descriptionEn: "Efficient AI-powered research: information retrieval, competitor analysis, industry trends, report generation, multi-source synthesis",
    layer: "foundation",
    level: 1, maxLevel: 3,
    departments: ["all"],
    pilotProjects: [],
    progress: 65,
    prerequisites: ["F02"],
    tools: ["Perplexity", "ChatGPT", "Claude"],
    tags: ["必修", "研究"],
  },
  {
    id: "F05",
    titleZh: "AI安全与合规",
    titleEn: "AI Safety & Compliance",
    descriptionZh: "了解AI使用的数据安全规范、隐私保护要求、版权合规、品牌风险防范、公司AI使用政策",
    descriptionEn: "Understand AI data security, privacy protection, copyright compliance, brand risk prevention, and company AI usage policies",
    layer: "foundation",
    level: 1, maxLevel: 2,
    departments: ["all"],
    pilotProjects: [],
    progress: 60,
    prerequisites: ["F01"],
    tools: [],
    tags: ["必修", "合规"],
  },
  {
    id: "F06",
    titleZh: "AI协作与知识共享",
    titleEn: "AI Collaboration & Knowledge Sharing",
    descriptionZh: "在团队中有效分享AI经验、协同使用AI工具、建立AI工作流、参与案例分享与双周学习",
    descriptionEn: "Share AI experiences in teams, collaborate on AI tools, build AI workflows, participate in case sharing and bi-weekly learning",
    layer: "foundation",
    level: 1, maxLevel: 2,
    departments: ["all"],
    pilotProjects: [],
    progress: 55,
    prerequisites: ["F01"],
    tools: [],
    tags: ["必修", "协作"],
  },

  // ========== MARKETING CENTER (营销中心) ==========
  {
    id: "MK01",
    titleZh: "AI广告投放优化",
    titleEn: "AI Ad Campaign Optimization",
    descriptionZh: "利用AI进行广告受众分析、出价策略优化、素材A/B自动测试、ROI预测与预算分配，覆盖Google/Meta/TikTok等平台",
    descriptionEn: "AI-powered audience analysis, bidding optimization, creative A/B testing, ROI prediction across Google/Meta/TikTok platforms",
    layer: "department",
    level: 2, maxLevel: 4,
    departments: ["marketing"],
    pilotProjects: ["marketing-ai"],
    progress: 45,
    prerequisites: ["F02", "F04"],
    tools: ["ChatGPT", "Google Ads AI", "Meta Advantage+", "TikTok Smart+"],
    tags: ["广告", "ROI", "投放"],
  },
  {
    id: "MK02",
    titleZh: "AI社媒内容创作",
    titleEn: "AI Social Media Content Creation",
    descriptionZh: "AI辅助生成社交媒体文案(Instagram/TikTok/Facebook/Pinterest)、话题策划、发布时间优化、UGC内容策展",
    descriptionEn: "AI-assisted social media copy for IG/TikTok/FB/Pinterest, topic planning, posting time optimization, UGC curation",
    layer: "department",
    level: 2, maxLevel: 4,
    departments: ["marketing"],
    pilotProjects: ["marketing-ai", "creative-ai"],
    progress: 52,
    prerequisites: ["F02", "F03"],
    tools: ["ChatGPT", "Jasper", "Canva AI", "CapCut"],
    tags: ["社媒", "内容", "创作"],
  },
  {
    id: "MK03",
    titleZh: "AI SEO/SEM优化",
    titleEn: "AI SEO/SEM Optimization",
    descriptionZh: "利用AI进行关键词研究与聚类、搜索广告文案优化、SEO内容策略、竞品搜索份额分析、长尾词挖掘",
    descriptionEn: "AI-powered keyword research, search ad copy optimization, SEO content strategy, competitor search share analysis",
    layer: "department",
    level: 2, maxLevel: 4,
    departments: ["marketing"],
    pilotProjects: ["marketing-ai"],
    progress: 38,
    prerequisites: ["F02", "F04"],
    tools: ["ChatGPT", "Semrush", "Ahrefs", "SurferSEO"],
    tags: ["SEO", "SEM", "搜索"],
  },
  {
    id: "MK04",
    titleZh: "AI邮件营销自动化",
    titleEn: "AI Email Marketing Automation",
    descriptionZh: "AI驱动的邮件个性化内容生成、主题行优化、发送时间预测、用户分群自动化、转化漏斗分析",
    descriptionEn: "AI-driven email personalization, subject line optimization, send time prediction, user segmentation, conversion funnel analysis",
    layer: "department",
    level: 2, maxLevel: 4,
    departments: ["marketing"],
    pilotProjects: ["marketing-ai"],
    progress: 30,
    prerequisites: ["F02"],
    tools: ["Klaviyo AI", "ChatGPT", "Mailchimp AI"],
    tags: ["邮件", "自动化", "个性化"],
  },
  {
    id: "MK05",
    titleZh: "AI KOL/红人营销",
    titleEn: "AI Influencer Marketing",
    descriptionZh: "AI辅助红人筛选与匹配、内容合作策划、效果预测与ROI分析、#CupsheCrew社区运营",
    descriptionEn: "AI-assisted influencer discovery & matching, content collaboration, performance prediction, #CupsheCrew community management",
    layer: "department",
    level: 3, maxLevel: 4,
    departments: ["marketing"],
    pilotProjects: ["marketing-ai"],
    progress: 20,
    prerequisites: ["MK02"],
    tools: ["Modash", "ChatGPT", "CreatorIQ"],
    tags: ["红人", "KOL", "社区"],
  },
  {
    id: "MK06",
    titleZh: "AI品牌舆情监控",
    titleEn: "AI Brand Sentiment Monitoring",
    descriptionZh: "利用AI实时监控品牌口碑(Trustpilot/社媒/论坛)、竞品动态、消费者情感分析、危机预警与应对",
    descriptionEn: "Real-time brand reputation monitoring across Trustpilot/social/forums, competitor tracking, sentiment analysis, crisis alerts",
    layer: "department",
    level: 2, maxLevel: 3,
    departments: ["marketing"],
    pilotProjects: [],
    progress: 25,
    prerequisites: ["F04"],
    tools: ["Brandwatch", "ChatGPT", "Sprinklr"],
    tags: ["舆情", "品牌", "监控"],
  },

  // ========== OPERATION CENTER (运营中心) ==========
  {
    id: "OP01",
    titleZh: "AI客服智能应答",
    titleEn: "AI Smart Customer Service",
    descriptionZh: "构建AI客服知识库(RAG)、自动回复系统、智能工单路由、多语言客服支持、客户情绪识别",
    descriptionEn: "Build AI customer service knowledge base (RAG), auto-reply system, smart ticket routing, multilingual support, emotion detection",
    layer: "department",
    level: 2, maxLevel: 4,
    departments: ["operations"],
    pilotProjects: [],
    progress: 68,
    prerequisites: ["F02"],
    tools: ["OpenAI API", "Zendesk AI", "Intercom"],
    tags: ["客服", "RAG", "知识库"],
  },
  {
    id: "OP02",
    titleZh: "AI用户评论分析",
    titleEn: "AI Review & Feedback Analysis",
    descriptionZh: "利用NLP分析用户评论(Amazon/独立站/社媒/Trustpilot)，提取产品洞察、尺码反馈、面料偏好、改进建议",
    descriptionEn: "NLP-powered review analysis across Amazon/DTC/social/Trustpilot for product insights, sizing feedback, fabric preferences",
    layer: "department",
    level: 2, maxLevel: 4,
    departments: ["operations", "product"],
    pilotProjects: ["data-ai"],
    progress: 40,
    prerequisites: ["F02", "F04"],
    tools: ["ChatGPT", "Python", "MonkeyLearn"],
    tags: ["评论", "NLP", "洞察"],
  },
  {
    id: "OP03",
    titleZh: "AI运营数据看板",
    titleEn: "AI Operations Dashboard",
    descriptionZh: "使用AI自动生成运营日报/周报、异常指标预警、趋势分析、自然语言数据查询",
    descriptionEn: "AI-generated daily/weekly reports, anomaly alerts, trend analysis, natural language data queries",
    layer: "department",
    level: 2, maxLevel: 3,
    departments: ["operations"],
    pilotProjects: ["data-ai"],
    progress: 35,
    prerequisites: ["F03"],
    tools: ["ChatGPT", "Tableau AI", "Google Sheets AI"],
    tags: ["报表", "看板", "自动化"],
  },
  {
    id: "OP04",
    titleZh: "AI用户生命周期管理",
    titleEn: "AI Customer Lifecycle Management",
    descriptionZh: "AI驱动的用户分群、流失预警、复购激励策略、LTV预测、个性化触达(邮件/短信/App推送)",
    descriptionEn: "AI-driven user segmentation, churn prediction, repurchase incentives, LTV prediction, personalized outreach",
    layer: "department",
    level: 3, maxLevel: 4,
    departments: ["operations"],
    pilotProjects: ["data-ai"],
    progress: 22,
    prerequisites: ["OP02", "OP03"],
    tools: ["Klaviyo", "ChatGPT", "Amplitude"],
    tags: ["用户", "LTV", "留存"],
  },
  {
    id: "OP05",
    titleZh: "AI促销策略优化",
    titleEn: "AI Promotion Strategy Optimization",
    descriptionZh: "利用AI进行促销定价模拟、折扣策略优化、库存联动促销、活动效果预测与复盘",
    descriptionEn: "AI-powered promotion pricing simulation, discount strategy optimization, inventory-linked promotions, campaign prediction",
    layer: "scenario",
    level: 3, maxLevel: 4,
    departments: ["operations", "marketing"],
    pilotProjects: ["marketing-ai"],
    progress: 15,
    prerequisites: ["OP03"],
    tools: ["ChatGPT", "Python", "内部BI"],
    tags: ["促销", "定价", "策略"],
  },

  // ========== MULTI CHANNEL (多渠道事业部) ==========
  {
    id: "MC01",
    titleZh: "AI Amazon运营优化",
    titleEn: "AI Amazon Operations",
    descriptionZh: "AI辅助Amazon Listing优化(标题/五点/描述/后台关键词)、A+内容生成、PPC广告自动化、评论管理与分析",
    descriptionEn: "AI-powered Amazon Listing optimization, A+ content generation, PPC automation, review management and analysis",
    layer: "department",
    level: 2, maxLevel: 4,
    departments: ["multi-channel"],
    pilotProjects: ["marketing-ai"],
    progress: 42,
    prerequisites: ["F02", "F04"],
    tools: ["ChatGPT", "Helium 10", "Jungle Scout"],
    tags: ["Amazon", "Listing", "PPC"],
  },
  {
    id: "MC02",
    titleZh: "AI多平台运营",
    titleEn: "AI Multi-Platform Operations",
    descriptionZh: "AI辅助Walmart/eBay/Temu/SHEIN等平台的产品上架、内容本地化、价格监控、竞品追踪",
    descriptionEn: "AI-assisted product listing, content localization, price monitoring, competitor tracking across Walmart/eBay/Temu/SHEIN",
    layer: "department",
    level: 2, maxLevel: 3,
    departments: ["multi-channel"],
    pilotProjects: [],
    progress: 28,
    prerequisites: ["F02"],
    tools: ["ChatGPT", "Keepa", "Prisync"],
    tags: ["多平台", "上架", "监控"],
  },
  {
    id: "MC03",
    titleZh: "AI跨平台数据整合",
    titleEn: "AI Cross-Platform Analytics",
    descriptionZh: "利用AI整合多平台(独立站+Amazon+Walmart等)销售数据、统一分析框架、跨渠道归因与预算优化",
    descriptionEn: "AI-powered multi-platform data integration, unified analytics framework, cross-channel attribution and budget optimization",
    layer: "scenario",
    level: 3, maxLevel: 4,
    departments: ["multi-channel", "operations"],
    pilotProjects: ["data-ai"],
    progress: 18,
    prerequisites: ["MC01", "OP03"],
    tools: ["ChatGPT", "Python", "Google BigQuery"],
    tags: ["跨平台", "归因", "数据"],
  },

  // ========== CHANNEL DEVELOPMENT (渠道拓展部) ==========
  {
    id: "CD01",
    titleZh: "AI渠道机会发现",
    titleEn: "AI Channel Opportunity Discovery",
    descriptionZh: "利用AI分析市场数据，发现新渠道机会(线下/批发/联名)、评估进入策略、竞争格局分析",
    descriptionEn: "AI-powered market analysis for new channel opportunities (offline/wholesale/collab), entry strategy evaluation",
    layer: "department",
    level: 2, maxLevel: 3,
    departments: ["channel-dev"],
    pilotProjects: [],
    progress: 20,
    prerequisites: ["F04"],
    tools: ["ChatGPT", "Perplexity", "SimilarWeb"],
    tags: ["渠道", "机会", "分析"],
  },
  {
    id: "CD02",
    titleZh: "AI合作伙伴评估",
    titleEn: "AI Partner Evaluation",
    descriptionZh: "AI辅助评估潜在合作伙伴与批发客户、合作方案生成、合同条款分析、风险评估",
    descriptionEn: "AI-assisted partner and wholesale customer evaluation, proposal generation, contract analysis, risk assessment",
    layer: "department",
    level: 2, maxLevel: 3,
    departments: ["channel-dev"],
    pilotProjects: [],
    progress: 15,
    prerequisites: ["F04"],
    tools: ["ChatGPT", "Claude"],
    tags: ["合作", "评估", "BD"],
  },

  // ========== PRODUCT CENTER (产品中心) ==========
  {
    id: "PD01",
    titleZh: "AI趋势预测与选品",
    titleEn: "AI Trend Forecasting & Product Selection",
    descriptionZh: "利用AI分析时尚趋势(社媒热度/搜索趋势/竞品动态)，辅助泳装/度假装/女装品类规划和选品决策",
    descriptionEn: "AI-powered fashion trend analysis (social buzz/search trends/competitor moves) for swimwear/resort/womenswear category planning",
    layer: "department",
    level: 2, maxLevel: 4,
    departments: ["product"],
    pilotProjects: ["data-ai"],
    progress: 48,
    prerequisites: ["F02", "F04"],
    tools: ["ChatGPT", "Google Trends", "WGSN", "Trendalytics"],
    tags: ["趋势", "选品", "品类"],
  },
  {
    id: "PD02",
    titleZh: "AI消费者洞察",
    titleEn: "AI Consumer Insights",
    descriptionZh: "AI驱动的消费者需求挖掘、用户画像构建、购买行为分析、尺码/面料/风格偏好洞察",
    descriptionEn: "AI-driven consumer demand mining, persona building, purchase behavior analysis, sizing/fabric/style preference insights",
    layer: "department",
    level: 2, maxLevel: 4,
    departments: ["product", "operations"],
    pilotProjects: ["data-ai"],
    progress: 35,
    prerequisites: ["F04"],
    tools: ["ChatGPT", "Python", "Google Analytics"],
    tags: ["消费者", "画像", "洞察"],
  },
  {
    id: "PD03",
    titleZh: "AI产品定价策略",
    titleEn: "AI Product Pricing Strategy",
    descriptionZh: "利用AI进行竞品价格监控、弹性定价模拟、促销定价优化、跨市场价格策略",
    descriptionEn: "AI-powered competitor price monitoring, elastic pricing simulation, promotional pricing optimization, cross-market pricing",
    layer: "scenario",
    level: 3, maxLevel: 4,
    departments: ["product"],
    pilotProjects: [],
    progress: 18,
    prerequisites: ["PD01"],
    tools: ["ChatGPT", "Python", "Prisync"],
    tags: ["定价", "竞品", "策略"],
  },
  {
    id: "PD04",
    titleZh: "AI产品文案生成",
    titleEn: "AI Product Copywriting",
    descriptionZh: "AI辅助生成产品描述、卖点提炼、多语言翻译(英/西/法/德)、SEO优化文案、A+/EBC内容",
    descriptionEn: "AI-generated product descriptions, USP extraction, multilingual translation, SEO-optimized copy, A+/EBC content",
    layer: "department",
    level: 2, maxLevel: 3,
    departments: ["product", "multi-channel"],
    pilotProjects: ["creative-ai"],
    progress: 55,
    prerequisites: ["F02"],
    tools: ["ChatGPT", "Claude", "DeepL"],
    tags: ["文案", "翻译", "SEO"],
  },

  // ========== CREATIVE CENTER (创意中心) ==========
  {
    id: "CR01",
    titleZh: "AI图像生成与编辑",
    titleEn: "AI Image Generation & Editing",
    descriptionZh: "掌握Midjourney/DALL-E/Stable Diffusion等工具，生成产品概念图、场景图、素材变体、背景替换",
    descriptionEn: "Master Midjourney/DALL-E/Stable Diffusion for product concepts, scene images, asset variants, background replacement",
    layer: "department",
    level: 2, maxLevel: 4,
    departments: ["creative"],
    pilotProjects: ["creative-ai"],
    progress: 62,
    prerequisites: ["F02"],
    tools: ["Midjourney", "DALL-E", "Stable Diffusion", "Adobe Firefly"],
    tags: ["图像", "生成", "设计"],
  },
  {
    id: "CR02",
    titleZh: "AI视频内容制作",
    titleEn: "AI Video Content Production",
    descriptionZh: "利用AI进行短视频脚本生成、视频剪辑辅助、字幕生成、多语言配音、产品展示视频自动化",
    descriptionEn: "AI-powered video script generation, editing assistance, subtitle generation, multilingual dubbing, product showcase automation",
    layer: "department",
    level: 2, maxLevel: 4,
    departments: ["creative", "marketing"],
    pilotProjects: ["creative-ai"],
    progress: 40,
    prerequisites: ["F02"],
    tools: ["CapCut", "Runway", "HeyGen", "ElevenLabs"],
    tags: ["视频", "剪辑", "配音"],
  },
  {
    id: "CR03",
    titleZh: "AI平面设计辅助",
    titleEn: "AI Graphic Design Assistance",
    descriptionZh: "AI辅助Banner设计、社媒图片、邮件模板、活动海报、独立站页面视觉的快速生成与迭代",
    descriptionEn: "AI-assisted banner design, social media graphics, email templates, campaign posters, DTC site visual generation",
    layer: "department",
    level: 2, maxLevel: 4,
    departments: ["creative"],
    pilotProjects: ["creative-ai", "marketing-ai"],
    progress: 50,
    prerequisites: ["CR01"],
    tools: ["Canva AI", "Adobe Firefly", "Figma AI"],
    tags: ["平面", "Banner", "模板"],
  },
  {
    id: "CR04",
    titleZh: "AI虚拟试穿与3D展示",
    titleEn: "AI Virtual Try-On & 3D Display",
    descriptionZh: "利用AI和3D技术实现虚拟试穿体验、产品360°展示、虚拟模特生成、AR试衣功能",
    descriptionEn: "AI + 3D technology for virtual try-on, 360° product display, virtual model generation, AR fitting room",
    layer: "scenario",
    level: 3, maxLevel: 5,
    departments: ["creative", "it"],
    pilotProjects: ["creative-ai"],
    progress: 12,
    prerequisites: ["CR01"],
    tools: ["CLO 3D", "Stable Diffusion", "Google ARCore"],
    tags: ["3D", "虚拟试穿", "AR"],
  },
  {
    id: "CR05",
    titleZh: "AI品牌视觉一致性",
    titleEn: "AI Brand Visual Consistency",
    descriptionZh: "利用AI确保跨渠道(独立站/Amazon/社媒/邮件)视觉一致性、品牌调性检测、风格迁移与统一",
    descriptionEn: "AI-powered cross-channel visual consistency (DTC/Amazon/social/email), brand tone detection, style transfer",
    layer: "scenario",
    level: 3, maxLevel: 4,
    departments: ["creative"],
    pilotProjects: ["creative-ai"],
    progress: 18,
    prerequisites: ["CR01", "CR03"],
    tools: ["Adobe Firefly", "Midjourney", "Brand Kit AI"],
    tags: ["品牌", "一致性", "视觉"],
  },

  // ========== SUPPLY CHAIN (生产供应链中心) ==========
  {
    id: "SC01",
    titleZh: "AI需求预测",
    titleEn: "AI Demand Forecasting",
    descriptionZh: "利用AI进行销量预测、季节性需求建模(泳装旺季/度假季)、新品销量估算、库存水位规划",
    descriptionEn: "AI-powered sales forecasting, seasonal demand modeling (swimwear/resort seasons), new product estimation, inventory planning",
    layer: "department",
    level: 2, maxLevel: 4,
    departments: ["supply-chain"],
    pilotProjects: ["data-ai"],
    progress: 30,
    prerequisites: ["F03"],
    tools: ["Python", "ChatGPT", "Prophet"],
    tags: ["预测", "需求", "库存"],
  },
  {
    id: "SC02",
    titleZh: "AI面辅料智能采购",
    titleEn: "AI Smart Fabric Procurement",
    descriptionZh: "AI辅助面料选择(舒适度/耐用性/环保)、供应商评估与比价、采购成本优化、交期预测",
    descriptionEn: "AI-assisted fabric selection (comfort/durability/eco), supplier evaluation, procurement cost optimization, lead time prediction",
    layer: "department",
    level: 2, maxLevel: 3,
    departments: ["supply-chain"],
    pilotProjects: [],
    progress: 22,
    prerequisites: ["F03"],
    tools: ["ChatGPT", "Python"],
    tags: ["采购", "面料", "供应商"],
  },
  {
    id: "SC03",
    titleZh: "AI品控与质检",
    titleEn: "AI Quality Control & Inspection",
    descriptionZh: "利用AI图像识别进行产品质量检测、缺陷分类、质量趋势分析、供应商质量评分",
    descriptionEn: "AI image recognition for quality inspection, defect classification, quality trend analysis, supplier quality scoring",
    layer: "scenario",
    level: 3, maxLevel: 4,
    departments: ["supply-chain"],
    pilotProjects: [],
    progress: 10,
    prerequisites: ["SC02"],
    tools: ["TensorFlow", "OpenCV", "ChatGPT"],
    tags: ["品控", "质检", "图像识别"],
  },
  {
    id: "SC04",
    titleZh: "AI生产排程优化",
    titleEn: "AI Production Scheduling",
    descriptionZh: "AI辅助生产计划排程、产能优化、多工厂协调、交期管理与风险预警",
    descriptionEn: "AI-assisted production scheduling, capacity optimization, multi-factory coordination, delivery management",
    layer: "scenario",
    level: 3, maxLevel: 4,
    departments: ["supply-chain"],
    pilotProjects: [],
    progress: 8,
    prerequisites: ["SC01"],
    tools: ["Python", "ChatGPT"],
    tags: ["排程", "产能", "生产"],
  },

  // ========== WAREHOUSING & LOGISTICS (仓储物流中心) ==========
  {
    id: "WL01",
    titleZh: "AI库存智能管理",
    titleEn: "AI Smart Inventory Management",
    descriptionZh: "AI驱动的库存水位预警、自动补货建议、滞销品识别、仓位优化、跨仓调拨策略",
    descriptionEn: "AI-driven inventory alerts, auto-replenishment, slow-mover identification, warehouse slot optimization, cross-warehouse transfers",
    layer: "department",
    level: 2, maxLevel: 4,
    departments: ["logistics"],
    pilotProjects: ["data-ai"],
    progress: 28,
    prerequisites: ["F03"],
    tools: ["Python", "ChatGPT", "内部WMS"],
    tags: ["库存", "补货", "仓储"],
  },
  {
    id: "WL02",
    titleZh: "AI物流路径优化",
    titleEn: "AI Logistics Route Optimization",
    descriptionZh: "利用AI优化跨境物流路径(中国→美国)、运费比价、时效预测、海关合规辅助",
    descriptionEn: "AI-optimized cross-border logistics routing (China→US), freight comparison, delivery time prediction, customs compliance",
    layer: "department",
    level: 2, maxLevel: 3,
    departments: ["logistics"],
    pilotProjects: [],
    progress: 15,
    prerequisites: ["F03"],
    tools: ["ChatGPT", "ShipStation"],
    tags: ["物流", "跨境", "路径"],
  },
  {
    id: "WL03",
    titleZh: "AI退换货分析",
    titleEn: "AI Returns & Exchange Analysis",
    descriptionZh: "AI分析退换货原因(尺码/质量/色差/描述不符)、预测退货率、优化退货流程、降低退货成本",
    descriptionEn: "AI analysis of return reasons (sizing/quality/color/description), return rate prediction, process optimization",
    layer: "department",
    level: 2, maxLevel: 3,
    departments: ["logistics", "operations"],
    pilotProjects: ["data-ai"],
    progress: 20,
    prerequisites: ["F03"],
    tools: ["ChatGPT", "Python"],
    tags: ["退换货", "分析", "优化"],
  },

  // ========== IT CENTER (互联网研发中心) ==========
  {
    id: "IT01",
    titleZh: "AI辅助编程",
    titleEn: "AI-Assisted Programming",
    descriptionZh: "使用Copilot/Cursor等AI编程工具提升开发效率、代码审查、Bug修复、单元测试生成",
    descriptionEn: "Use Copilot/Cursor AI coding tools for development efficiency, code review, bug fixing, unit test generation",
    layer: "department",
    level: 2, maxLevel: 4,
    departments: ["it"],
    pilotProjects: [],
    progress: 70,
    prerequisites: ["F02"],
    tools: ["GitHub Copilot", "Cursor", "Claude"],
    tags: ["编程", "开发", "效率"],
  },
  {
    id: "IT02",
    titleZh: "AI推荐系统开发",
    titleEn: "AI Recommendation Engine Development",
    descriptionZh: "构建和优化AI驱动的商品推荐引擎、个性化首页、搜索排序、\"猜你喜欢\"功能",
    descriptionEn: "Build and optimize AI-powered product recommendation engine, personalized homepage, search ranking, 'You May Also Like'",
    layer: "scenario",
    level: 3, maxLevel: 5,
    departments: ["it"],
    pilotProjects: ["data-ai"],
    progress: 25,
    prerequisites: ["IT01"],
    tools: ["Python", "TensorFlow", "AWS Personalize"],
    tags: ["推荐", "个性化", "算法"],
  },
  {
    id: "IT03",
    titleZh: "AI数据管道与ETL",
    titleEn: "AI Data Pipeline & ETL",
    descriptionZh: "利用AI优化数据采集、清洗、转换流程，构建智能数据管道，实现数据质量自动监控",
    descriptionEn: "AI-optimized data collection, cleaning, transformation pipelines with automated data quality monitoring",
    layer: "department",
    level: 3, maxLevel: 4,
    departments: ["it"],
    pilotProjects: ["data-ai"],
    progress: 30,
    prerequisites: ["IT01"],
    tools: ["Python", "dbt", "Airflow", "ChatGPT"],
    tags: ["数据", "ETL", "管道"],
  },
  {
    id: "IT04",
    titleZh: "AI模型部署与运维",
    titleEn: "AI Model Deployment & MLOps",
    descriptionZh: "AI模型的容器化部署、性能监控、A/B测试框架、模型版本管理、自动化迭代",
    descriptionEn: "AI model containerized deployment, performance monitoring, A/B testing framework, model versioning, automated iteration",
    layer: "system",
    level: 4, maxLevel: 5,
    departments: ["it"],
    pilotProjects: [],
    progress: 12,
    prerequisites: ["IT01", "IT03"],
    tools: ["Docker", "Kubernetes", "MLflow"],
    tags: ["MLOps", "部署", "运维"],
  },
  {
    id: "IT05",
    titleZh: "AI安全与防欺诈",
    titleEn: "AI Security & Fraud Prevention",
    descriptionZh: "利用AI进行交易欺诈检测、账号安全防护、DDoS防护、异常行为识别、支付风控",
    descriptionEn: "AI-powered fraud detection, account security, DDoS protection, anomaly detection, payment risk control",
    layer: "scenario",
    level: 3, maxLevel: 4,
    departments: ["it"],
    pilotProjects: [],
    progress: 18,
    prerequisites: ["IT01"],
    tools: ["Python", "AWS GuardDuty", "Stripe Radar"],
    tags: ["安全", "防欺诈", "风控"],
  },

  // ========== FINANCE CENTER (财务中心) ==========
  {
    id: "FN01",
    titleZh: "AI财务分析与预测",
    titleEn: "AI Financial Analysis & Forecasting",
    descriptionZh: "利用AI进行财务数据分析、现金流预测、预算编制辅助、盈利能力分析、财务报告生成",
    descriptionEn: "AI-powered financial analysis, cash flow forecasting, budget planning, profitability analysis, report generation",
    layer: "department",
    level: 2, maxLevel: 4,
    departments: ["finance"],
    pilotProjects: ["data-ai"],
    progress: 32,
    prerequisites: ["F03"],
    tools: ["ChatGPT", "Python", "Excel AI"],
    tags: ["财务", "预测", "分析"],
  },
  {
    id: "FN02",
    titleZh: "AI智能对账与审计",
    titleEn: "AI Smart Reconciliation & Audit",
    descriptionZh: "AI辅助自动对账(多平台/多币种)、异常交易识别、审计线索发现、合规检查",
    descriptionEn: "AI-assisted auto-reconciliation (multi-platform/multi-currency), anomaly detection, audit trail discovery, compliance checks",
    layer: "department",
    level: 2, maxLevel: 3,
    departments: ["finance", "audit"],
    pilotProjects: [],
    progress: 20,
    prerequisites: ["F03"],
    tools: ["ChatGPT", "Python", "内部ERP"],
    tags: ["对账", "审计", "合规"],
  },
  {
    id: "FN03",
    titleZh: "AI汇率与跨境成本管理",
    titleEn: "AI FX & Cross-Border Cost Management",
    descriptionZh: "利用AI进行汇率风险预测、跨境支付成本优化、多币种利润分析、税务合规辅助",
    descriptionEn: "AI-powered FX risk prediction, cross-border payment optimization, multi-currency profit analysis, tax compliance",
    layer: "scenario",
    level: 3, maxLevel: 4,
    departments: ["finance"],
    pilotProjects: [],
    progress: 10,
    prerequisites: ["FN01"],
    tools: ["ChatGPT", "Python", "Bloomberg AI"],
    tags: ["汇率", "跨境", "成本"],
  },

  // ========== GM OFFICE (总经办) ==========
  {
    id: "GM01",
    titleZh: "AI战略决策支持",
    titleEn: "AI Strategic Decision Support",
    descriptionZh: "利用AI进行市场分析、竞争格局研判、战略方案评估、行业对标分析、投资机会筛选",
    descriptionEn: "AI-powered market analysis, competitive landscape assessment, strategy evaluation, industry benchmarking",
    layer: "department",
    level: 3, maxLevel: 4,
    departments: ["gm-office"],
    pilotProjects: [],
    progress: 25,
    prerequisites: ["F04"],
    tools: ["ChatGPT", "Claude", "Perplexity"],
    tags: ["战略", "决策", "分析"],
  },
  {
    id: "GM02",
    titleZh: "AI经营分析报告",
    titleEn: "AI Business Analysis Reports",
    descriptionZh: "AI自动生成经营分析报告、KPI追踪看板、异常预警、管理层简报、董事会材料辅助",
    descriptionEn: "AI-generated business analysis reports, KPI dashboards, anomaly alerts, executive briefings, board material assistance",
    layer: "department",
    level: 2, maxLevel: 3,
    departments: ["gm-office"],
    pilotProjects: ["data-ai"],
    progress: 30,
    prerequisites: ["F03"],
    tools: ["ChatGPT", "Python", "Tableau"],
    tags: ["报告", "KPI", "经营"],
  },

  // ========== HR CENTER (人力资源中心) ==========
  {
    id: "HR01",
    titleZh: "AI招聘与人才筛选",
    titleEn: "AI Recruitment & Talent Screening",
    descriptionZh: "AI辅助简历筛选、人才画像匹配、面试问题生成、候选人评估、招聘渠道效果分析",
    descriptionEn: "AI-assisted resume screening, talent profile matching, interview question generation, candidate evaluation",
    layer: "department",
    level: 2, maxLevel: 3,
    departments: ["hr"],
    pilotProjects: [],
    progress: 28,
    prerequisites: ["F02"],
    tools: ["ChatGPT", "LinkedIn AI"],
    tags: ["招聘", "人才", "筛选"],
  },
  {
    id: "HR02",
    titleZh: "AI培训与发展",
    titleEn: "AI Training & Development",
    descriptionZh: "利用AI进行培训需求分析、个性化学习路径推荐、培训效果评估、知识库构建",
    descriptionEn: "AI-powered training needs analysis, personalized learning path recommendations, training effectiveness evaluation",
    layer: "department",
    level: 2, maxLevel: 3,
    departments: ["hr"],
    pilotProjects: [],
    progress: 22,
    prerequisites: ["F02"],
    tools: ["ChatGPT", "Claude"],
    tags: ["培训", "发展", "学习"],
  },
  {
    id: "HR03",
    titleZh: "AI组织效能分析",
    titleEn: "AI Organizational Effectiveness",
    descriptionZh: "AI驱动的组织诊断、人效分析、离职预测、敬业度分析、组织架构优化建议",
    descriptionEn: "AI-driven organizational diagnosis, workforce efficiency analysis, attrition prediction, engagement analysis",
    layer: "scenario",
    level: 3, maxLevel: 4,
    departments: ["hr"],
    pilotProjects: ["data-ai"],
    progress: 12,
    prerequisites: ["HR01", "HR02"],
    tools: ["ChatGPT", "Python", "内部HRIS"],
    tags: ["组织", "人效", "分析"],
  },

  // ========== AUDIT (审计监察部) ==========
  {
    id: "AU01",
    titleZh: "AI合规风控",
    titleEn: "AI Compliance & Risk Control",
    descriptionZh: "利用AI进行合规检查自动化、风险预警、异常行为监测、内控流程优化",
    descriptionEn: "AI-powered compliance automation, risk alerts, anomaly behavior monitoring, internal control optimization",
    layer: "department",
    level: 2, maxLevel: 3,
    departments: ["audit"],
    pilotProjects: [],
    progress: 15,
    prerequisites: ["F04"],
    tools: ["ChatGPT", "Python"],
    tags: ["合规", "风控", "审计"],
  },

  // ========== BOARD SECRETARY (董秘办) ==========
  {
    id: "BS01",
    titleZh: "AI信息披露辅助",
    titleEn: "AI Disclosure & IR Assistance",
    descriptionZh: "AI辅助公告撰写、合规审查、投资者关系管理、股东沟通材料生成、信息披露合规检查",
    descriptionEn: "AI-assisted announcement drafting, compliance review, investor relations, shareholder communication, disclosure compliance",
    layer: "department",
    level: 2, maxLevel: 3,
    departments: ["board-secretary"],
    pilotProjects: [],
    progress: 10,
    prerequisites: ["F03"],
    tools: ["ChatGPT", "Claude"],
    tags: ["信息披露", "IR", "合规"],
  },

  // ========== PILOT PROJECT ADVANCED (试点项目专项进阶) ==========
  // 效果营销AI化
  {
    id: "PM01",
    titleZh: "AI全链路归因分析",
    titleEn: "AI Full-Funnel Attribution",
    descriptionZh: "掌握AI驱动的多触点归因模型(首次/末次/线性/时间衰减/数据驱动)，优化营销预算跨渠道分配",
    descriptionEn: "Master AI-driven multi-touch attribution models to optimize cross-channel marketing budget allocation",
    layer: "system",
    level: 4, maxLevel: 5,
    departments: ["marketing", "multi-channel"],
    pilotProjects: ["marketing-ai"],
    progress: 8,
    prerequisites: ["MK01", "MC03"],
    tools: ["Google Analytics 4", "Python", "ChatGPT"],
    tags: ["归因", "全链路", "预算"],
  },
  {
    id: "PM02",
    titleZh: "AI创意素材规模化生产",
    titleEn: "AI Creative Asset Scaling",
    descriptionZh: "实现广告创意的AI批量生成、自动A/B测试、效果优化闭环，支撑千人千面投放",
    descriptionEn: "AI-powered batch creative generation, automated A/B testing, optimization loop for personalized ad delivery at scale",
    layer: "system",
    level: 4, maxLevel: 5,
    departments: ["marketing", "creative"],
    pilotProjects: ["marketing-ai", "creative-ai"],
    progress: 5,
    prerequisites: ["MK01", "CR03"],
    tools: ["Midjourney API", "ChatGPT", "Meta Creative Hub"],
    tags: ["规模化", "创意", "自动化"],
  },
  {
    id: "PM03",
    titleZh: "AI受众智能拓展",
    titleEn: "AI Audience Intelligence & Expansion",
    descriptionZh: "利用AI进行Lookalike受众扩展、跨平台用户匹配、精准定向、高价值用户预测",
    descriptionEn: "AI-powered lookalike audience expansion, cross-platform user matching, precision targeting, high-value user prediction",
    layer: "system",
    level: 4, maxLevel: 5,
    departments: ["marketing"],
    pilotProjects: ["marketing-ai"],
    progress: 5,
    prerequisites: ["MK01", "OP04"],
    tools: ["Meta Advantage+", "Google AI", "ChatGPT"],
    tags: ["受众", "定向", "拓展"],
  },
  // 创意AI化
  {
    id: "PC01",
    titleZh: "AI设计系统构建",
    titleEn: "AI Design System Development",
    descriptionZh: "建立AI驱动的品牌设计系统，确保CUPSHE视觉输出一致性和效率，包含模板库、风格指南、自动化流程",
    descriptionEn: "Build AI-driven brand design system ensuring CUPSHE visual consistency and efficiency with template library and style guide",
    layer: "system",
    level: 4, maxLevel: 5,
    departments: ["creative"],
    pilotProjects: ["creative-ai"],
    progress: 8,
    prerequisites: ["CR01", "CR05"],
    tools: ["Figma AI", "Midjourney", "Adobe Firefly"],
    tags: ["设计系统", "品牌", "一致性"],
  },
  {
    id: "PC02",
    titleZh: "AI内容工厂",
    titleEn: "AI Content Factory",
    descriptionZh: "构建AI内容批量生产流水线：从创意brief到成品的自动化流程，覆盖图片/视频/文案全链路",
    descriptionEn: "Build AI content mass production pipeline: automated workflow from creative brief to final asset across image/video/copy",
    layer: "system",
    level: 4, maxLevel: 5,
    departments: ["creative", "marketing"],
    pilotProjects: ["creative-ai"],
    progress: 5,
    prerequisites: ["CR01", "CR02", "CR03"],
    tools: ["Midjourney", "Runway", "ChatGPT", "CapCut"],
    tags: ["内容工厂", "批量", "自动化"],
  },
  {
    id: "PC03",
    titleZh: "AI创意效果预测",
    titleEn: "AI Creative Performance Prediction",
    descriptionZh: "利用AI预测创意素材的市场表现(点击率/转化率/互动率)，辅助创意决策，减少试错成本",
    descriptionEn: "AI-powered creative performance prediction (CTR/CVR/engagement), data-driven creative decisions, reduced trial-and-error",
    layer: "system",
    level: 4, maxLevel: 5,
    departments: ["creative", "marketing"],
    pilotProjects: ["creative-ai", "marketing-ai"],
    progress: 3,
    prerequisites: ["CR03", "MK01"],
    tools: ["Meta Creative Hub", "ChatGPT", "Python"],
    tags: ["预测", "创意", "效果"],
  },
  // 数据分析AI化
  {
    id: "DA01",
    titleZh: "AI自助式数据分析",
    titleEn: "AI Self-Service Analytics",
    descriptionZh: "使用自然语言查询数据库、生成可视化报表、自动发现数据洞察，让非技术人员也能做数据分析",
    descriptionEn: "Natural language database queries, auto-generated visualizations, automated insight discovery for non-technical users",
    layer: "system",
    level: 3, maxLevel: 5,
    departments: ["operations", "marketing", "product", "finance", "gm-office"],
    pilotProjects: ["data-ai"],
    progress: 15,
    prerequisites: ["F03"],
    tools: ["ChatGPT", "Tableau AI", "ThoughtSpot"],
    tags: ["自助分析", "可视化", "洞察"],
  },
  {
    id: "DA02",
    titleZh: "AI预测建模",
    titleEn: "AI Predictive Modeling",
    descriptionZh: "构建业务预测模型：销量预测、用户行为预测、库存预测、流失预测，支撑数据驱动决策",
    descriptionEn: "Build business prediction models: sales forecasting, user behavior prediction, inventory prediction, churn prediction",
    layer: "system",
    level: 4, maxLevel: 5,
    departments: ["it", "operations", "supply-chain"],
    pilotProjects: ["data-ai"],
    progress: 10,
    prerequisites: ["IT03"],
    tools: ["Python", "TensorFlow", "Prophet", "ChatGPT"],
    tags: ["预测", "建模", "机器学习"],
  },
  {
    id: "DA03",
    titleZh: "AI数据叙事",
    titleEn: "AI Data Storytelling",
    descriptionZh: "利用AI将数据分析结果转化为业务故事，自动生成管理层报告、投资者简报、经营分析",
    descriptionEn: "AI-powered data-to-story transformation for executive reports, investor briefings, business analysis narratives",
    layer: "system",
    level: 3, maxLevel: 4,
    departments: ["gm-office", "finance", "operations"],
    pilotProjects: ["data-ai"],
    progress: 12,
    prerequisites: ["F03", "F04"],
    tools: ["ChatGPT", "Claude", "Gamma"],
    tags: ["数据叙事", "报告", "管理层"],
  },
];
