CREATE TABLE `weekly_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`weekId` varchar(16) NOT NULL,
	`centerId` varchar(64) NOT NULL,
	`centerName` varchar(255) NOT NULL,
	`centerNameEn` varchar(255),
	`status` enum('red','yellow','green') NOT NULL,
	`progressPercent` int DEFAULT 0,
	`maturityLevel` enum('L1','L2','L3','L4','L5') DEFAULT 'L1',
	`progressItems` text,
	`issues` text,
	`nextWeekPlans` text,
	`highlights` text,
	`activeAiUsers` int DEFAULT 0,
	`newCasesCount` int DEFAULT 0,
	`skillsUnlocked` int DEFAULT 0,
	`isPilot` boolean DEFAULT false,
	`submittedBy` int,
	`submitterName` varchar(255),
	`ceoReviewNote` text,
	`ceoReviewed` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `weekly_reports_id` PRIMARY KEY(`id`)
);
